name: add comment to issue

on:
  issues:
    types: [opened]
  



jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: dump github event context
        run: echo '${{ toJSON(github.event) }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment for ${{ github.event.repository.name }} for issue ${{ github.event.issue.title }}.
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
        
  