name: add comment to issue

on:
  issues:
    types: [opened]
permissions:
  issues: write


jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Context
        run: echo '${{ toJSON(github.event) }}'

      - name: Debug Inputs
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Body: ${{ github.event.issue.title }}"

      - name: Enable Debugging
        run: echo "{{ secrets.GITHUB_TOKEN }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment 
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
          reactions: '+1'