name: Test Workflow

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  FirstJob:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running first job"

  SecondJob:
    runs-on: ubuntu-latest
    needs: FirstJob
    
    steps:
      - name: Run a script
        run: echo "Running second job after first job"